# action.yml
name: "DWP Kitchen Terraform"
description: "Run kitchen terraform commands: github.com/newcontext-oss/kitchen-terraform"
branding:
  icon: "git-pull-request"
  color: "black"
inputs:
  kitchen-command:
    description: "The command to run for example: list, converge, verify, test, destroy, etc."
    required: true
  aws-account-number:
    description: "AWS account number, used to redact from kitchen/terraform output"
    required: true
runs:
  using: "docker"
  image: "docker://quay.io/dwp/kitchen-terraform:0.14.7"
  args:
    - ${{ inputs.kitchen-command }}
    - ${{ inputs.aws-account-number }}
