# action.yml
name: "DWP Kitchen Terraform"
description: "Run kitchen terraform commands: github.com/newcontext-oss/kitchen-terraform"
branding:
  icon: "git-pull-request"
  color: "black"
inputs:
  kitchen-command:
    description: "The command to run for example: list, converge, verify, test, destroy, etc."
    required: true
  aws-account-number:
    description: "AWS account number, used to redact from kitchen/terraform output"
    required: true
  terraform-version:
    description: "Terraform version to use. Supported versions (tags) listed here: https://github.com/dwp/github-action-kitchen-terraform/pkgs/container/github-action-kitchen-terraform"
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/dwp/github-action-kitchen-terraform:2.0.0"
  env:
    TFENV_TERRAFORM_VERSION: ${{ inputs.terraform-version}}
  args:
    - ${{ inputs.kitchen-command }}
    - ${{ inputs.aws-account-number }}
