name: PR

on:
  pull_request:
    paths-ignore:
      - "**/*.md"

env:
  KICS_user_is_root: 67fd0c4a-68cf-46d7-8c41-bc9fba7e40ae

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Ruby Version
        uses: ruby/setup-ruby@v1
      - name: Build Docker image
        run: docker build -t kitchen-terraform:latest .
      - name: Check container [kitchen converge]
        run: docker run --rm -v $(pwd)/examples/check-container:/usr/action kitchen-terraform:latest "converge"
      - name: Check container [kitchen verify]
        run: docker run --rm -v $(pwd)/examples/check-container:/usr/action kitchen-terraform:latest "verify"

  kics-scan:
    name: KICS Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "repo"
      - name: KICS Github Action
        uses: checkmarx/kics-action@v1.5
        with:
          path: "repo"
          output_path: "results"
          exclude_queries: ${{ env.KICS_user_is_root }}
          fail_on: high,medium
          enable_comments: true
