on:
  push:
    branches:
      - main
    paths:
      - '.release-please-manifest.json'
name: publish-containers
jobs:
  publish-containers:
    name: Build & Publish Containers
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Get release number
        id: get-release
        run: |
          RELEASE=$(sed 's/"."/"key"/g' .release-please-manifest.json | jq -r .key)
          echo ${RELEASE}
          echo ::set-output name=release-number::${RELEASE}

      - name: Show version
        run: |
          echo "Version: ${{ steps.get-release.outputs.release-number }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            RUBY_VERSION=3.1.2
            TERRAFORM_VERSIONS=0.14.7 1.2.4 1.2.5
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get-release.outputs.release-number }}
            quay.io/dwp/kitchen-terraform:${{ steps.get-release.outputs.release-number }}
            dwpdigital/kitchen-terraform:${{ steps.get-release.outputs.release-number }}
